### ISSUE TITLE
some question 

### ISSUE THREAD

**Issue by boxyao** [gdlg/pytorch_nms#6]
There are some thing wrong  with my NMS testing.
I create test.py file under the folder /src
ImportError: cannot import name 'details' from 'src.nms' 
How to handle this error?

**Comment by gdlg** [comment]
It is difficult to provide an answer without more details (content of test.py, output of the program and exactly how you run it).

However nms.details is a C++ extension built and installed by setup.py. So in order for it to work, you must use `python setup.py install` which will install the library to your site_packages.
If you have done that, you might still encounter this error if you try to run your test.py from the src/ folder. This is because your test.py might try to import the Python files from the src folder rather than those installed in site_packages. In that case, move your test.py somewhere else and it should work.

**Comment by boxyao** [comment]
Thank you very much, After I upgrade GCC and pytorch, I can running from nms import nms after import torch.  Fantastic~，Thank you very very much~

**Comment by gdlg** [comment]
Great that it works. I have seen issues too depending on the import order of PyTorch.
